<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Envioprovee extends Model
{
   
    use HasFactory;
    protected $fillable = [
    'dia', 
    'description',
    'duracion',
    'fechain',
    'fechafi',
    'asistente',
    'observAsistente',
    'recoge',
    'telefrecibe',
    'autoriza',
    'nombreauto',
    'correoautorizadores',
    'ids',
    'profesional',
    'unidadAutori',
    'jefeautori',
    'nombresolici',
    'username',
    'centrocosto',
    'observCentrocosto',
    'correoautori',
    'Nombreprove',
    'Correoelectroni',
    'Teléfono',
    'nombrecontactouno',
    'telefonouno',
    'nombrecontactodos',
    'telefonodos',
    'fechasoliciuno',
    'horauno',
    'lugaruno',
    'persrecibe',
    'producto',
    'cantidad',
    'valorunid',
    'valortota',
    'fechasolicidos',
    'horados',
    'lugardos',
    'persrecibedos',
    'productodos',
    'cantidaddos',
    'valoruniddos',
    'valortotados',
    "fechasolicitres",
    "horatres" ,
    "lugartres" ,
    "persrecibetres",
    "productotres" ,
    "cantidatres" ,
    "valorunidtres" ,
    "valortotatres" ,
    "fechasolicicuatro" ,
    "horacuatro" ,
    "lugarcuatro",
    "persrecibecuatro" ,
    "productocuatro",
    "cantidadcuatro",
    "valorunidcuatro",
    "valortotacuatro",
    "fechasolicicinco" ,
    "horacinco" ,
    "lugarcinco",
    "persrecibecinco" ,
    "productocinco" ,
    "cantidadcinco" ,
    "valorunidcinco",
    "valortotacinco" ,
    "valortotalfinal" ,
    "observacion" ,
    "estado" ,
    "email_jefe",
    "email" ,
    "jefe" ,
    "jefenombre",
    "observacionincomplet",
    'mas',
    ];
}
